version: '3.9'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"

  backend:
    image: stepan186/kisilya
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    ports:
      - "8000:8000"

